# Linear algebra in python with NumPy
## Numpy is one of the most used libraries in python for arrays manipulation. It adds to python a set of functions that allows us to operate on large multidimensional arrays with just few lines.

In [1]:
import numpy as np

# Defining Lists and numpy arrays

In [3]:
alist = [1,2,3,4,5]             # ordinary python list
narray = np.array([1,2,3,4,5])  # numpy array

## Note the difference between Python list and a NumPy Array


In [4]:
print(alist, narray, type(alist), type(narray), sep='\n')

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


# Algebraic operators on NumPy arrays vs. Python lists
## Note the '+' operator on numpy arrays perform an element-wise addition, while the same operation on Python lists results in a list concatenation.

In [5]:
print(narray + narray)
print(alist + alist)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## It is the same as with the product, ```*```. In the first case, we scale vector, while in the second case, we concatenate three times the same list.

In [6]:
print(narray*3)
print(alist *3)

[ 3  6  9 12 15]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# Matrix Array of Arrays:
## With Numpy, we have two ways to create a matrix:
- Creating an array of arrays ```np.array``` (recommended).
- Creating a matrix using ```np.matrix``` (still available but might be removed soon)

In [8]:
npmatrix1 = np.array([narray, narray, narray]) # Matrix inialized with Numpy arrays
npmatrix2 = np.array([alist, alist, alist]) # Matrix inialized with lists
npmatrix3 = np.array([narray, [1,1,1,1,1], narray]) # Matrix inialized with both Numpy types

print(npmatrix1, npmatrix2, npmatrix3, sep='\n')

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 1 1 1 1]
 [1 2 3 4 5]]


## However, when defining a matrix, be sure that all the rows contain the same number of elements. Otherwise, the linear algebra operations could lead to unexpected results.

## Analyze the following examples:

In [9]:
# Example 1:

okmatrix = np.array([[1,2],[3,4]]) # 2 x 2 matrix
print(okmatrix)
print(okmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [17]:
# Example 2

badmatrix = np.array([[1,2],[3,4], [5,6,7]])
print(badmatrix)
print(badmatrix * 2)

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


<ipython-input-17-f6d0bbb10cad>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  badmatrix = np.array([[1,2],[3,4], [5,6,7]])


# Scaling and translating matrices
## Now that you know how to build correct NumPy arrays and matrices, let us see how easy it is to operate with them in python using the regular algebric operators like ```+``` and ```-```.
## Operations can be performed between arrays and arrays or between arrays and scalars.

In [18]:
# Scale by 2 and translate 1 unit the matrix
result = okmatrix * 2 + 1 # for each element in the matrix, multiply by 2 and add 1
print(result) 

[[3 5]
 [7 9]]


In [19]:
print(okmatrix + okmatrix)
print(okmatrix - okmatrix)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


## The operator ```*``` when used on arrays or matrices indicates element- wise multiplications. Do not confuse it with the **dot** product.

In [20]:
result = okmatrix * okmatrix
print(result)

[[ 1  4]
 [ 9 16]]


# Transpose of a matrix

## **T** denotes the transpose operations with NumPy matrices.

In [21]:
mat3x2 = np.array([[1,2],[3,4],[5,6]])
print("Original Matrix:\n", mat3x2)
print("Transposed Matrix:\n", mat3x2.T)

Original Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Matrix:
 [[1 3 5]
 [2 4 6]]


## How ever, note that the transpose operation does not affect 1D arrays.

In [22]:
nparray = np.array([1,2,3,4,5])
print("Original:", nparray, "Transposed:", nparray.T, sep="\n" )

Original:
[1 2 3 4 5]
Transposed:
[1 2 3 4 5]


## Perhaps in this case you wanted to do:

In [23]:
nparray = np.array([[1,2,3,4,5]])
print("Original:", nparray, "Transposed:", nparray.T, sep="\n" )

Original:
[[1 2 3 4 5]]
Transposed:
[[1]
 [2]
 [3]
 [4]
 [5]]


# Get the norm of a nparray or matrix
## in linear algebra, the norm of an n-dimensional vector $\vec{a}$ is defined as:
$$
norm(\vec{a}) = \mid\mid\vec{a}\mid\mid \\= \sqrt{\sum_{i=1}^{n} a_{i}^2}
$$

## Calculating the norm of the vector or even of a matrix is a general operation when dealing with data. Numpy has a set of functions for linear algebra in the subpackage **linakg**, including the norm function. Let us see how to get the norm of a given array or matrix:

In [24]:
nparray1 = np.array([1,2,3,4])
norm1 = np.linalg.norm(nparray1)

nparray2 = np.array([[1,2], [3,4]])
norm2 = np.linalg.norm(nparray2)

print(norm1, norm2, sep="\n")

5.477225575051661
5.477225575051661
