# Exercise:

In [1]:
import numpy as np
import pandas as pd

## Create two numpy array of size 3 x 2 and 2 x 3

In [2]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[6,5],[4,3],[2,1]])
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]]
[[6 5]
 [4 3]
 [2 1]]


## Randomly initialize that array

In [3]:
random_array = np.random.randint(low=1, high=100, size=(3,3))
print(random_array)

[[44 84 15]
 [49 17 75]
 [82 22 90]]


## Perform matrix multiplication

In [4]:
product_mat = np.dot(array1, array2)
print(product_mat)

[[20 14]
 [56 41]]


## Perform element wise matrix multiplication

In [7]:
res = [[0 for i in range(len(array1))] for j in range(len(array2[0]))]

for i in range(len(array1)):
    for j in range(len(array2[0])):
        for k in range(len(array2)):
            res[i][j] += array1[i][k] * array2[k][j]

print(res)

[[20, 14], [56, 41]]


## Mean of First matrix

In [8]:
mean = np.mean(array1)
print(mean)

3.5


## Convert numeric entries(columns) of mtcars.csv to Mean Centered Version

In [9]:
main_data = pd.read_csv('mtcars.csv')

In [10]:
del main_data['model']

# meancenter
meancenter = main_data.apply(lambda x: x - x.mean())
print(meancenter.head())

        mpg     cyl        disp       hp      drat       wt     qsec      vs  \
0  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.59725 -1.38875 -0.4375   
1  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.34225 -0.82875 -0.4375   
2  2.709375 -2.1875 -122.721875 -53.6875  0.253437 -0.89725  0.76125  0.5625   
3  1.309375 -0.1875   27.278125 -36.6875 -0.516563 -0.00225  1.59125  0.5625   
4 -1.390625  1.8125  129.278125  28.3125 -0.446563  0.22275 -0.82875 -0.4375   

        am    gear    carb  
0  0.59375  0.3125  1.1875  
1  0.59375  0.3125  1.1875  
2  0.59375  0.3125 -1.8125  
3 -0.40625 -0.6875 -1.8125  
4 -0.40625 -0.6875 -0.8125  
