# Linear algebra in python with NumPy
## Numpy is one of the most used libraries in python for arrays manipulation. It adds to python a set of functions that allows us to operate on large multidimensional arrays with just few lines.

In [1]:
import numpy as np

# Defining Lists and numpy arrays

In [2]:
alist = [1,2,3,4,5]             # ordinary python list
narray = np.array([1,2,3,4,5])  # numpy array

## Note the difference between Python list and a NumPy Array


In [3]:
print(alist, narray, type(alist), type(narray), sep='\n')

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


# Algebraic operators on NumPy arrays vs. Python lists
## Note the '+' operator on numpy arrays perform an element-wise addition, while the same operation on Python lists results in a list concatenation.

In [4]:
print(narray + narray)
print(alist + alist)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## It is the same as with the product, ```*```. In the first case, we scale vector, while in the second case, we concatenate three times the same list.

In [5]:
print(narray*3)
print(alist *3)

[ 3  6  9 12 15]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# Matrix Array of Arrays:
## With Numpy, we have two ways to create a matrix:
- Creating an array of arrays ```np.array``` (recommended).
- Creating a matrix using ```np.matrix``` (still available but might be removed soon)

In [6]:
npmatrix1 = np.array([narray, narray, narray]) # Matrix inialized with Numpy arrays
npmatrix2 = np.array([alist, alist, alist]) # Matrix inialized with lists
npmatrix3 = np.array([narray, [1,1,1,1,1], narray]) # Matrix inialized with both Numpy types

print(npmatrix1, npmatrix2, npmatrix3, sep='\n')

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 1 1 1 1]
 [1 2 3 4 5]]


## However, when defining a matrix, be sure that all the rows contain the same number of elements. Otherwise, the linear algebra operations could lead to unexpected results.

## Analyze the following examples:

In [7]:
# Example 1:

okmatrix = np.array([[1,2],[3,4]]) # 2 x 2 matrix
print(okmatrix)
print(okmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [8]:
# Example 2

badmatrix = np.array([[1,2],[3,4], [5,6,7]])
print(badmatrix)
print(badmatrix * 2)

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


<ipython-input-8-f6d0bbb10cad>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  badmatrix = np.array([[1,2],[3,4], [5,6,7]])


# Scaling and translating matrices
## Now that you know how to build correct NumPy arrays and matrices, let us see how easy it is to operate with them in python using the regular algebric operators like ```+``` and ```-```.
## Operations can be performed between arrays and arrays or between arrays and scalars.

In [9]:
# Scale by 2 and translate 1 unit the matrix
result = okmatrix * 2 + 1 # for each element in the matrix, multiply by 2 and add 1
print(result) 

[[3 5]
 [7 9]]


In [10]:
print(okmatrix + okmatrix)
print(okmatrix - okmatrix)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


## The operator ```*``` when used on arrays or matrices indicates element- wise multiplications. Do not confuse it with the **dot** product.

In [11]:
result = okmatrix * okmatrix
print(result)

[[ 1  4]
 [ 9 16]]


# Transpose of a matrix

## **T** denotes the transpose operations with NumPy matrices.

In [12]:
mat3x2 = np.array([[1,2],[3,4],[5,6]])
print("Original Matrix:\n", mat3x2)
print("Transposed Matrix:\n", mat3x2.T)

Original Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Matrix:
 [[1 3 5]
 [2 4 6]]


## How ever, note that the transpose operation does not affect 1D arrays.

In [13]:
nparray = np.array([1,2,3,4,5])
print("Original:", nparray, "Transposed:", nparray.T, sep="\n" )

Original:
[1 2 3 4 5]
Transposed:
[1 2 3 4 5]


## Perhaps in this case you wanted to do:

In [14]:
nparray = np.array([[1,2,3,4,5]])
print("Original:", nparray, "Transposed:", nparray.T, sep="\n" )

Original:
[[1 2 3 4 5]]
Transposed:
[[1]
 [2]
 [3]
 [4]
 [5]]


# Get the norm of a nparray or matrix
## in linear algebra, the norm of an n-dimensional vector $\vec{a}$ is defined as:
$$
norm(\vec{a}) = \mid\mid\vec{a}\mid\mid \\= \sqrt{\sum_{i=1}^{n} a_{i}^2}
$$

## Calculating the norm of the vector or even of a matrix is a general operation when dealing with data. Numpy has a set of functions for linear algebra in the subpackage **linakg**, including the norm function. Let us see how to get the norm of a given array or matrix:

In [15]:
nparray1 = np.array([1,2,3,4])
norm1 = np.linalg.norm(nparray1)

nparray2 = np.array([[1,2], [3,4]])
norm2 = np.linalg.norm(nparray2)

print(norm1, norm2, sep="\n")

5.477225575051661
5.477225575051661


## Note that without any other parameter, the norm function treats the matrix as being just an array of numbers. However, it is possible to get the norm by rows or by columns. The **axis** parameter controls the form of the operation:
- **axis=0** means get the norm of each column.
- **axis=1** means get the norm of each row.

In [17]:
nparray2 = np.array([[1,1],[2,2],[3,3]])
normByCols = np.linalg.norm(nparray2, axis=0)
normByRows = np.linalg.norm(nparray2, axis=1)

print(normByCols, normByRows, sep='\n')

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


# The dot product between arrays: All the flavors
## The dot product or scalar product or inner product between two vectors $\vec{a}$ and $\vec{b}$ of same size is defined as:
$$
\vec{a} \, \cdot \vec{b} = \sum_{i=1}^{n} a_{i}b{i}
$$
## The dot product takes two vectors and returns a single number

In [18]:
nparray1 = np.array([0,1,2,3])
nparray2 = np.array([4,5,6,7])

flavor1 = np.dot(nparray1, nparray2)
print(flavor1)

flavor2 = np.sum(nparray1 * nparray2)
print(flavor2)

flavor3 = nparray1 @ nparray2
print(flavor3)

flavor4 = 0
for a,b in zip(nparray1, nparray2):
    flavor4 += a*b
print(flavor4)

38
38
38
38


## Recommend ```np.dot()``` as it is the only method that accepts arrays and lists without problems.

In [20]:
norm1 = np.dot(np.array([1,2]), np.array([3,4]))
norm2 = np.dot([1,2], [3,4])

print(norm1, norm2, sep='\n')
print('norm1 == norm2: ', norm1 == norm2)

11
11
norm1 == norm2:  True


## Finally, not that the norm is the square root of the dot product of the vector with itself.
$$
norm(\vec{a})\, =\,\, \mid\mid\vec{a}\mid\mid
= \sqrt{\sum_{i=1}^{n} a_{i}^2} = \sqrt{a \cdot a} 
$$

# Sums by rows or columns
## another general operation performed on the matrices is the sum by rows or columns. Just as we did for the function norm, the axis parameter controls the form of the operation:
- **axis = 0** means to sum the elements of each column together.
- **axis = 1** means to sum the elements of each row together.

In [21]:
nparray2 = np.array([[1,-1], [2,-2], [3,-3]])

sumByCols = np.sum(nparray2, axis = 0)
sumByRows = np.sum(nparray2, axis = 1)

print('Sum by columns:', sumByCols)
print('Sum by rows', sumByRows)

Sum by columns: [ 6 -6]
Sum by rows [0 0 0]


# Get the mean by rows or columns
$$
mean(\vec{a}) = \frac{\sqrt{\sum_{i=1}^{n} a_{i}}}{n}
$$

In [22]:
nparray2 = np.array([[1,-1], [2,-2], [3,-3]])

mean = np.mean(nparray2)
meanbyCols = np.mean(nparray2, axis=0)
meanbyRows = np.mean(nparray2, axis=1)

print('Mean:', mean)
print('Mean by cols:', meanbyCols)
print('Mean by rows:', meanbyRows)

Mean: 0.0
Mean by cols: [ 2. -2.]
Mean by rows: [0. 0. 0.]


# Center the columns of a matrix
## Centering the attributes of a data matrix essential preprocessing step. Considering a matrix means to remove the column mean to each element inside the column. The sum by columns of a centered matrix is always 0.
## With NumPy, this process is as simple as this.

In [25]:
nparray2 = np.array([[1,1],[2,2],[3,3]])

nparrayCentered = nparray2 - np.mean(nparray2, axis = 0)
print("Original matrix:", nparray2, sep='\n')
print("Centered matrix:", nparrayCentered, sep='\n')

print('New mean by cols:', nparrayCentered.mean(axis=0))

Original matrix:
[[1 1]
 [2 2]
 [3 3]]
Centered matrix:
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by cols: [0. 0.]


## **Warning:** This process does not apply for row centering. In such case, consider transposing the matrix, centering by columns, and then transpose back the result.
## See the example below:

In [26]:
nparray2 = np.array([[1,3],[2,4],[3,5]])

nparrayCentered = nparray2.T - np.mean(nparray2, axis=1)
nparrayCentered = nparrayCentered.T

print("Original Matrix", nparray2, sep='\n')
print("Centered by cols:", nparrayCentered, sep='\n')
print("Centered by rows", nparrayCentered.mean(axis=1))

Original Matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by cols:
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
Centered by rows [0. 0. 0.]


# Exercise

# Create two numpy array of size 3x2 and 2x3