# Task 1
## Try Linear Regression just using numpy (*Without Tensorflow/Pytorch or other torch library*). You can optionally use sklearn (if you want)

In [13]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [14]:
# Temperature, rainfall, humidity

input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],
                    [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],
                    [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                    dtype='float32')
print(input.shape)

(15, 3)


In [15]:
# apple, oranges

target = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(input, target, test_size=0.3, random_state=88)

In [17]:
lr = LinearRegression().fit(X_train, Y_train)
print(lr)

LinearRegression()


In [18]:
print(lr.intercept_)
print(lr.coef_)

[-2.7205505 -2.1424255]
[[-0.38055605  0.842811    0.7128339 ]
 [-0.28565016  0.79435384  0.92394835]]


In [19]:
Y_pred = lr.predict(X_test)
print(Y_pred,"\n")
print(Y_test)

[[ 21.07846   37.064564]
 [101.82931  119.08207 ]
 [ 82.437584 100.89925 ]
 [118.45212  133.03842 ]
 [118.45212  133.03842 ]] 

[[ 22.  37.]
 [103. 119.]
 [ 81. 101.]
 [119. 133.]
 [119. 133.]]


In [20]:
from sklearn import metrics

print(f'Mean Squared Error: {metrics.mean_squared_error(Y_test, Y_pred)}')

Mean Squared Error: 0.4910760223865509
